name: Run PHPUnit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
#          extensions: mbstring, curl, openssl, json
          coverage: none

      - name: Check current working directory
        run: pwd

      - name: Change directory to root
        run: cd ..  # Aquest pas canvia a la carpeta pare, on està el fitxer composer.json

      - name: Check current working directory
        run: pwd

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Run PHPUnit tests
        run: |
          bin/phpunit
